export type ServiceKeypoint = {
  category: "Dev" | "MKT" | "Design";
  label: string;
};

export const serviceKeypoints: ServiceKeypoint[] = [
  { category: "Dev", label: "Shopify theme" },
  { category: "Dev", label: "Custom apps" },
  { category: "Dev", label: "Headless storefront" },
  { category: "Dev", label: "Theme 2.0 sections" },
  { category: "Dev", label: "App extensions" },
  { category: "Dev", label: "Replatforming" },
  { category: "Dev", label: "Shopify Plus" },
  { category: "Dev", label: "Performance builds" },
  { category: "Dev", label: "Medusa commerce" },
  { category: "Dev", label: "Twenty CRM" },
  { category: "Dev", label: "Odoo ERP" },
  { category: "Dev", label: "Strapi CMS" },
  { category: "Dev", label: "WordPress" },
  { category: "Dev", label: "Haravan" },
  { category: "Dev", label: "Claude code support" },
  { category: "Dev", label: "AI maintenance" },
  { category: "Dev", label: "AI workflows" },
  { category: "Dev", label: "Hydrogen storefront" },
  { category: "Dev", label: "API integrations" },
  { category: "Dev", label: "Webhook automation" },
  { category: "Dev", label: "Payment gateways" },
  { category: "Dev", label: "Inventory sync" },
  { category: "MKT", label: "Paid ads" },
  { category: "MKT", label: "Content strategy" },
  { category: "MKT", label: "SEO" },
  { category: "MKT", label: "CRO" },
  { category: "MKT", label: "Growth retainer" },
  { category: "MKT", label: "Social campaigns" },
  { category: "MKT", label: "Analytics" },
  { category: "MKT", label: "Linear analysis" },
  { category: "MKT", label: "Quantitative analysis" },
  { category: "MKT", label: "Funnel analysis" },
  { category: "MKT", label: "Cohort tracking" },
  { category: "MKT", label: "Attribution modeling" },
  { category: "MKT", label: "ROAS optimization" },
  { category: "MKT", label: "Customer segmentation" },
  { category: "MKT", label: "Heatmap insights" },
  { category: "MKT", label: "Conversion paths" },
  { category: "MKT", label: "Competitor research" },
  { category: "MKT", label: "KPI dashboards" },
  { category: "MKT", label: "GA4 & pixels" },
  { category: "MKT", label: "Meta ads" },
  { category: "MKT", label: "TikTok ads" },
  { category: "MKT", label: "Email automation" },
  { category: "MKT", label: "LTV modeling" },
  { category: "Design", label: "Lifestyle imagery" },
  { category: "Design", label: "Material ecom" },
  { category: "Design", label: "Social content" },
  { category: "Design", label: "Retouch style" },
  { category: "Design", label: "High resolution" },
  { category: "Design", label: "Award-worthy UI" },
  { category: "Design", label: "Typography systems" },
  { category: "Design", label: "Product imagery" },
  { category: "Design", label: "Brand aesthetics" },
  { category: "Design", label: "Motion UI" },
  { category: "Design", label: "3D product renders" },
  { category: "Design", label: "Lookbook design" },
  { category: "Design", label: "Packaging mockups" },
  { category: "Design", label: "Color systems" },
  { category: "Design", label: "Iconography" },
];
